67 java
green-code-initiative/creedengo-java pull request #44
Opened 2024-05-30 08:52 UTC by pataluc

Rule now only reports when `i++` is in statement.

Issue #4

2024-05-30 11:54 UTC, cyChop commented
Quid d'un test case (compliant) `int a = 2 + counter++` ?
(Normalement couvert par `bar61(2 + counter++)`, mais ce cas était également déjà couvert par `bar61(counter++)`.)

2024-05-30 13:14 UTC, pataluc commented
> Quid d'un test case (compliant) `int a = 2 + counter++` ? (Normalement couvert par `bar61(2 + counter++)`, mais ce cas était également déjà couvert par `bar61(counter++)`.)

après discussion avec @dedece35 hier, au final on ne cherche que les cas ou le parent de `i++` est une `Kind.EXPRESSION_STATEMENT`, parce que les autres cas sont soit volontaires, soit des code smells déjà reporté par les règles Sonar hors ecocode. du coup je ne suis pas sûr que cela apporte qqchose de rajouter ce cas (même si c'est très simple de l'ajouter)

2024-05-31 21:07 UTC, dedece35 commented
> > Quid d'un test case (compliant) `int a = 2 + counter++` ? (Normalement couvert par `bar61(2 + counter++)`, mais ce cas était également déjà couvert par `bar61(counter++)`.)
> 
> après discussion avec @dedece35 hier, au final on ne cherche que les cas ou le parent de `i++` est une `Kind.EXPRESSION_STATEMENT`, parce que les autres cas sont soit volontaires, soit des code smells déjà reporté par les règles Sonar hors ecocode. du coup je ne suis pas sûr que cela apporte qqchose de rajouter ce cas (même si c'est très simple de l'ajouter)

Hello ... merci pour la précision ... mais peut-être qu'on s'est mal compris, perso, je serai aussi pour checker le uses case de @cyChop même si je pense qu'il est déjà couvert (ça ne coute rien de rajouter un cas de test dans les fichiers de tests et voir ce qui se passe en TU, puis en test env reel et vérifier si SonarQube remonte déjà un code smell natif sur ces cas là)
Donc, je préfère tout de meme rajouter du check et du test pour vérifier please.

2024-05-31 21:08 UTC, dedece35 requested changes
cf les commentaires ci-dessus

2025-05-20 15:12 UTC, max-208 commented
see [rules-spec #317](https://github.com/green-code-initiative/creedengo-rules-specifications/pull/317)

2025-05-21 06:48 UTC, pataluc commented
#Challenge2025, to review by @dedece35 and @cyChop ;)

2025-05-21 11:43 UTC, cyChop commented
Les test cases ajoutés couvrent tous les cas auxquels je peux penser, OK pour moi.

2025-05-25 08:47 UTC, utarwyn reviewed
Can you rebase your branch on the main branch?
I have pushed a fix to correct the build 😊

2025-05-25 19:49 UTC, pataluc commented
> Can you rebase your branch on the main branch? I have pushed a fix to correct the build 😊

just did it ;)

2025-05-25 20:10 UTC, utarwyn approved these changes
Thank you for the work on this! LGTM 💯 
Waiting for @dedece35 to review and merge asap

2025-05-25 21:05 UTC, dedece35 approved these changes

2025-05-25 21:06 UTC, dedece35 commented
thank you @pataluc ! good job !

2025-05-25 21:06 UTC, merged